version: "3.4"
services:
  rocketpool-testnet.public.dappnode.eth:
    image: "rocketpool-testnet.public.dappnode.eth:0.1.0"
    build:
      context: ./build
      args:
        UPSTREAM_VERSION: v1.9.1
    volumes:
      - "rocketpool-testnet:/rocketpool"
    environment:
      - NETWORK=prater
      - WALLET_PASSWORD=mydappnode12
      - "BRAIN_API=http://brain.web3signer-prater.dappnode:3000"
      - EXTRA_OPTS=
    restart: unless-stopped
    ports:
      - "3000:3000"
volumes:
  rocketpool-testnet: {}
