version: "3.4"
services:
  rocketpool.dnp.dappnode.eth:
    image: "rocketpool.dnp.dappnode.eth:0.1.0"
    build:
      context: ./build
      args:
        UPSTREAM_VERSION: v1.10.0
        NETWORK: mainnet
    volumes:
      - "rocketpool:/rocketpool"
    environment:
      - NETWORK=mainnet
      - WALLET_PASSWORD=
      - EXTRA_OPTS=
    restart: unless-stopped
volumes:
  rocketpool: {}
